### ISSUE TITLE
Does not support Hierarchical presentation

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#283] opened 2017-08-06 06:07 UTC
When creating new multi-module project, and switching to Hierarchical presentation, the modules are not shown under root project.

![image](https://user-images.githubusercontent.com/1614482/29001044-7aa61772-7ab0-11e7-848e-bede7969faee.png)

**Comment by paulvi** [comment] 2017-08-06 06:10
maven example 

![image](https://user-images.githubusercontent.com/1614482/29001059-fb396ab0-7ab0-11e7-9436-eae9b1235f5e.png)

**Comment by paulvi** [comment] 2017-08-06 06:13
OK, I could get wished result creating general project for the root 

![image](https://user-images.githubusercontent.com/1614482/29001073-63992c4e-7ab1-11e7-8ea9-7d942cbf607a.png)

**Comment by de-jcup** [comment] 2017-08-21 07:30
I never used the project explorer but always only package explorer and navigator. The virtual root project was designed to have an additonal project inside the package explorer, containing only the parts you do not have visible because of missing root project.

If you add a general project and use the project explorer -as in your screenshot above - it seems you do not have to use "virtual root project" any more because then you already have the root parts.
In my opinion - if you use **only** the project explorer - you can delete the virtual root project because you have no benefits.

I think the creation of a general project and reuse it in project explorer is a good way to present the hierarchy. Maybe I could automate this in future.

**Comment by de-jcup** [comment] 2017-08-28 07:08
@paulvi - Inside the "new project wizard" of EGradle I could create (for multi projects ) a checbox with options:
```
[X] create virtual root project, 
[ ] create full root project (for hierarchical view in project explorer)
```
So it would be integrated inside the wizard. 

What do you think about his solution-approach?

**Comment by paulvi** [comment] 2017-09-18 11:57
Can it be simpler as `[x] create project for root`   
that may be of any needed type. (enabled by default)

Make less surprises for users.

**Comment by de-jcup** [comment] 2021-02-28 00:05
Sorry not enough time - will close this issue.

**Closed** 2021-02-28 00:06 UTC
Labels: wontfix
