### ISSUE TITLE
Global root project

### ISSUE THREAD

**Issue by oganga** [de-jcup/egradle#269] opened 2017-06-15 19:36 UTC
Question:
Not sure I get the idea with the "global" root project?

So far EGradle appear to be the a great plugin for working with gradle in Eclipse. For that thumbs up.

At least for me it was not apparent that the menu setting from the Window->Preferences->EGradle where not just some global config and going to Properties->Egradle on a specific project where not project specific.

Having the config as a global and not a project specific also leads to the concept of "Switching root project".
I have not come across a similar way of doing things in other Eclipse tools/plugins.

**Comment by de-jcup** [comment] 2017-06-18 19:34
Hallo @oganga, I appreciate your question about why using global root config instead of project specific information. I wrote some lines, remembered my decisions and did also some new thoughts (see next lines). 

Maybe it is possible to change the global root project approach to a project centric approach in future. But I am not sure how many people would need it. It's not some easy change to do this. 

Here my thoughts:

## Before EGradle

I was very frustrated by other gradle integrations when it comes around with handling gradle projects in eclipse, because a simple "cleanEclipse eclipse" on console destroyed my workspace setup and I had to fix it manually.
The reason for this behaviour was that the projects did always have an own eclipse project nature which was not supported by gradle on "eclipse" task and necessary meta information got lost on a "cleanEclipse eclipse" call on console.

## So what I did with EGradle
So my approach was to let the eclipse project setup configured by gradle itself and DO NOT change the standard. So eclipse and console "worlds" do not influence each other and are same.

The only special thing is the "virtual root project" which is always generated by EGradle when pressing the "(re)create virtual root" toolbar button.

## Why "global root project"
In my work I normally develop at one multi project at one time. So I did a KISS approach and let EGradle work only with one gradle configuration. After some time I was no longer a friend od the "global root project" idea and thought about some workarounds:

#153 (switch global root)
#90
#6

## Where do we need gradle information?
1. launch configurations
2. junit launch configuration
3. virtual root project 
4. quick launch 
5. ~editor~ (no dependency)
6. EGradle importer(gradle setup should become project specific and global settings would not be overriden - thats all)
7. EGradle new project wizard (gradle setup should become project specific and global settings would not be overriden - thats all)
8. Refresh eclipse dependencies (when project specific, the quick action would have to execute for all projects)
9. Junit import (what is the current project to look into)
 
## What are the problems to support different gradle projects inside one eclipse workspace?

### Setup configuration
EGradle may NOT influence ".project" information. The logic must remain in gradle for this (a big difference to other gradle integrations in eclipse..). Simple checkout sources, make a "cleanEclipse eclipse" must always work! I don't want to check .project files into GIT only to have some eclipse plugins working correct.

#### How to do this with every project?
~~So a "normal" eclipse way about setting "project->properties->EGradle" would not work (it would be very easy to implement it, but this would~~
It could be done: .egradle folder is generated for virtual root projects already, maybe some additional information could be stored there too. https://stackoverflow.com/questions/21269281/eclipse-nature-specific-project-properties does show how to add overlay pages inside properties (for a simple IProject instance/adapter...). So it seems no special project nature is necessary to get a custom property page.

##### How to get egradle project information after clean GIT checkout of projects?
When checkout of project sources is done, there exists no .egradle folder and no special EGradle setup. hmmm...  
When you run a new launch configuration (junit, normal) for this project and there exists no project info EGradle could prompt a dialog showing default configuration from current gradle root configuration and you must apply setup before execution can be done. So it would be automatically updated.

### Virtual root project
The virtual root project is currently always on top of project explorer/package explorer. And there is only ONE virtual root project at time.
When supporting project specific configurations for each multi project there must always exist a virtual root project.

So quick launch action ("(re)create virtual root project" would become "("(re)create virtual root projects"

### Quick-Launch
Quick launch mechanism does need a context where to run. Currently its always global root. 
When we got project specific gradle setup the current active project could be used - but in my opinion this would confuse users too much.

### Launch configurations + Junit launch configurations
With #6 I wanted to have launch configurations remembering where to run. If we would have got project information here and projects would support meta information about position
and gradle metainformation this would be much better.

### Junit-Import
A little bit tricky - which would be the project to scan for results to show in Junit-View? Currently I have no Idea how to solve this by supporting the former simply approach of "one-click"

**Comment by oganga** [comment] 2017-06-19 20:14
Wow....did not expect my question would result in such a long answer!!
Thank you for taking your time to do the write up.

I am only just getting my feet wet regarding Gradle. Have been working with Maven for some years. 
Always wondered why Eclipse failed to have a proper Maven and/or Gradle plugin before recent time.

Would not mind to give a hand. But starting from zero regarding Gradle and Eclipse Plugins it is bit of a mouth full before I would be able to and anything constructive to what you have written above or the project as such.
Sorry :)

One initial idea though: Have you looked at have the Maven plugin is behaves?

**Comment by paulvi** [comment] 2017-10-09 05:36
#299 was likely duplicate of this

I think it is just wrong to have Gradle root project in Preferences,
as it is should be property of a project in workspace, not setting for whole workspace.

![image](https://user-images.githubusercontent.com/1614482/31237688-3e078928-aa2a-11e7-878f-2f43d578d1c3.png)

P.S. @oganga yes, currently EGradle does it differently from m2e maven integration and others,  
and that is issue for new users.

**Comment by de-jcup** [comment] 2021-02-28 00:09
Sorry not enough time - will close this issue.

**Closed by de-jcup** 2021-02-28 00:09 UTC
